const {Nuxt} = require('nuxt');
const https = require('https');
const isProd = (process.env.NODE_ENV === 'production');
const port = process.env.PORT || 3000;
const config = require('./nuxt.config.js');
config.dev = !isProd;
const nuxt = new Nuxt(config);
const options = {};
https.createServer(options, nuxt.render).listen(port);
console.log('Server listening on `localhost:' + port + '`.');
